routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	 return view('welcome');
});
Route::resource('movie','MovieController');
	Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=> 'MovieController@destroy']);
	Route::post('movie/show',['as'=>'movie/show','uses'=>'MovieController@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Movie extends Model
{
   protected $table='movies';
   protected $fillable=['name','description'];
   protected $guarded=['id'];
}

app/Models/State.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    protected $table='states';
    protected $fillable=['state'];
    protected $guarded=['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Movie as Movie;

class MovieController extends Controller
{
    //mostrar
    public function edit($id)
    {
    $movie=Movie::find($id);
    return \View::make('movies/update',compact('movie'));
    }
    public function index(){

        
        $movies=Movie::all();
        return \View::make('movies/list',compact('movies'));
      
    }

    
	public function create()
	{
       return \View::make('movies/new');
	}

    // acciones
    public function show(Request $Request){
       $movies=Movie::where('name','like','%'.$Request->name.'%')->get();
       return \View::make('movies/list',compact('movies'));
    }
    public function update($id,Request $Request){
       $movie=Movie::find($id);
       $movie->name=$Request->name;
       $movie->description=$Request->description;
       $movie->save();
       return redirect('movie');
    }

    public function destroy($id){
        $movie=Movie::find($id);
        $movie->delete();
        return redirect()->back();
    }


    public function store(Request $Request)
    {
    	$movie=new Movie;
    	/*$movie->name=$Request->name;
    	$movie->description=$Request->description;
    	$movie->save();*/
    	$movie->create($Request->all());
    	return redirect('movie');

    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
@yield('content')
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

resources/views/movies/list.blade.php
@extends('layouts.app')
@section('content')
<section class="container">
	<div class='row'>
		<article class="col-md-12">

			{!! Form::open(['route' => 'movie/show', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
             <div class="form-group">
             	<label>Name</label>
             	<input type="text"  class="form-control" name="name">
             </div>
             <div class="form-group">
             	<button type="submit" class="btn btn-secondary">Search</button>
             	<a href="{{ route('movie.index') }}" class="btn btn-primary">All</a>
             	<a href="{{ route('movie.create') }}" class="btn btn-primary">create</a>
             </div>
			{!! Form::close()!!}
		</article>
		<article class="col-md-12">
			<table class="table table-condensed table-striped table-bordered">
				<thead>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Action</th>
			    </tr>
				</thead>
				<tbody>
					@foreach($movies as $movie)
					<tr>
						<td>{{ $movie->name }}</td>
						<td>{{ $movie->description}}</td>
						<td>
							<a href="{{ route('movie.edit',['id' => $movie->id]) }}" class="btn btn-primary btn-xs">Edit</a>
							<a href="{{ route('movie/destroy',['id' => $movie->id]) }}" class="btn btn-danger btn-xs">Delete</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</article>
	</div>
</section>

@endsection

resources/views/movies/new.blade.php
 @extends('layouts.app')
@section('content')
<section class="container">
	<div class="row">
		<article class="col-md-10 col-md-offset-1 ">
			{!! Form::open(['route' => 'movie.store', 'method' => 'post', 'novalidate']) !!}
			<div class="form-group">
				<label>name</label>
				<input type="text" name="name" class="form-control" required>
			</div>
			<div class="form-group">
				<label>Description</label>
				<input type="text" name="description" class="form-control" required>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-success">Enviar</button>
			</div>
			{!! Form::close() !!}
		</article>
	</div>
</section>
@endsection

resources/views/movies/update.blade.php
@extends('layouts.app')
@section('content')
<section class="container">
	<div class="row">
		<article class="Col-md-10 Col-md-offset-1">
			{!! Form::model($movie,['route' => ['movie.update',$movie->id], 'method' => 'put', 'novalidate']) !!}
			   <div class="form-group">
			   	<label>Name</label>
			   	<input type="text" name="name" required value="{{ $movie->name }}" class="form-control">
			   </div>
			   <div class="form-group">
			   	<label>Description</label>
			   	<input type="text" name="description" required value="{{ $movie->description }}" class="form-control">
			   </div>
			   <div class="form-group">
			   	<button type="submit" class="btn btn-success">Enviar</button>
			   </div>
			{!! Form::close() !!}
		</article>
	</div>
</section> 
@endsection